### ISSUE TITLE
Different icons per mode

### ISSUE THREAD

**Issue by sabi0** [StevenRudenko/LocationModeTile#1]
It would be nice to have a different icon for each of the modes.
It would help to differentiate the modes when the tile is among the first 6 "collapsed" ones.

Here is an idea how such icons could look like:
![image](https://user-images.githubusercontent.com/11509875/36618037-e2088a62-18e9-11e8-9709-d9b89aa0c05e.png)
![image](https://user-images.githubusercontent.com/11509875/36618376-3cd53c0a-18eb-11e8-9f65-bdb964351ab6.png)
![image](https://user-images.githubusercontent.com/11509875/36618589-fadda0d4-18eb-11e8-87fd-4f76e3e53505.png)

P.S. The app main icon also deserves a change. The app is not shown in the application drawer. But distinct icon would help in the list of installed apps or when browsing .apks in the Download folder.

**Comment by StevenRudenko** [comment]
very nice idea. will definitely add it. do you have an SVG source for those icons?

**Comment by sabi0** [comment]
I don't have SVGs, sorry. (I mocked up the icons in Paint)

**Comment by StevenRudenko** [comment]
np. I was able to create own SVGs. please check release 2.0. it has icons and new way to switch modes

**Comment by sabi0** [comment]
That was quick! Thank you.
I think however that "inner elements" should be made more "expressive".

It is very difficult to recognize a tiny "battery" on this icon:
![image](https://user-images.githubusercontent.com/11509875/38800650-1deb0720-4168-11e8-8f80-0661ee3cf9c5.png)
It is fine like that to differentiate the modes. But it would be great if icons were also "self describing".
E.g. you could try making the battery "tip" a little bigger.

**Comment by StevenRudenko** [comment]
ok. will take a look on it today's evening

**Comment by StevenRudenko** [comment]
@sabi0 could you please try v2.1. it has updated icons
